### ISSUE TITLE
Multiple divisions support

### ISSUE THREAD

**Issue by sbahir** [axel3rd/mpg-coach-bot#129]
Hello

Thanks for the repo !
It seems however that it crashes when a league is composed of multiple divisions : the league ID found is associated with the entire league, but there is an another unique ID for every division. It causes for a crash in : 
```
Exception in thread "main" java.lang.NullPointerException
	at org.blondin.mpg.Main.processLeague(Main.java:83)
	at org.blondin.mpg.Main.process(Main.java:75)
	at org.blondin.mpg.Main.main(Main.java:64)
```

**Comment by axel3rd** [comment]
Hi @sbahir,

Thanks for your report. I'm not sure to understand what you mean by "multiple divisions" : The only case I known is the Champions League, and it's not currently supported by this program.

Can you confirm you are using the version 1.5 ?

Did you have the capacity to share here the JSON content of the `GET https://api.monpetitgazon.com/user/dashboard` when you connect to MPG via a browser ? See Wiki [Get MPG data for opening a bug](https://github.com/axel3rd/mpg-coach-bot/wiki/Get-MPG-data-for-opening-a-bug) about howto retrieve JSON content from your browser.

Many thanks

**Comment by thomasGuerin3** [comment]
@sbahir talks about these leagues : 

![image](https://user-images.githubusercontent.com/43245220/67088421-64875780-f1a5-11e9-8b97-429a8613cf4e.png)

Theses leagues are composed of multiple divisions indeed. 

The dashboard json is like this : 

`"data": {
    "leagues": [
      {
      "id": "<id of the league>",
      ...
      //NO championship field here!!!
       ...
      ...
      "league": {
          "id": "<id of the subLeague>",
          "leagueStatus": 4,
          "championship": 1,
          ...
      }
`

So, in term of object, in your League.java, you need to add a new field `league` .

And in your Main.java, you should test if `league.getChampionship() == null`, if it's true, then this is because the league you're dealing with has a subLeague, so you can dig deeper to find the `league.getLeague()`

**Comment by axel3rd** [comment]
@thomasGuerin3 : Thanks for the precision, I did not have this feature in mind. 

To implement this support, is there possible to have the **complete** JSON  of `GET https://api.monpetitgazon.com/user/dashboard` (as file or copy/paste) ? 
It is not trivial to have a correct implementation without the complete structure.
The leagues id and/or names could  be anonymised if you want.

Many thanks

**Comment by axel3rd** [comment]
> It is not trivial to have a correct implementation without the complete structure.

@thomasGuerin3 / @sbahir : For sample, some other field are required (`name`, `mode`, ...), and the current JSON extract doesn't give information of location (*league* or  *subleague*). 
And I have not some leagues with more than 10 players, so can't test by myself.

Thanks for your help 🆘 

---

PR #130 as draft.

**Comment by sbahir** [comment]
Hi @axel3rd @thomasGuerin3  
Thanks for for the reactivity
Here is an example:
`json
{
  "success": true,
  "masterLeague": {
    "id": "mpg_master_league_<LEAGUE_ID>",
    "type": "mpg_master_league",
    "admin": "mpg_user_<USER_ID>",
    "status": 4,
    "season": 1,
    "name": "<LEAGUE_NAME>",
    "message": "<LEAGUE_MESSAGE>",
    "rating": "mpg",
    "championship": 2,
    "divisions": {
      "1": {
        "name": "Division 1",
        "users": [
          {
            "id": "mpg_user_<USER_ID_1>",
            "movement": 0
          },
          {
            "id": "mpg_user_<USER_ID_2>",
            "movement": 0
          },
         .....
        ],
        "id": "1",
        "leagueId": "mpg_league_<DIVISION_1_LEAGUE_ID>",
        "mercatoClosed": true
      },
      "2": {
        "name": "Division 2",
        "users": [
          {
            "id": "mpg_user_<USER_ID_3>",
            "movement": 0
          },
          {
            "id": "mpg_user_<USER_ID_4>",
            "movement": 0
          },
         .....
        ],
        "id": "2",
        "leagueId": "mpg_league_<DIVISION_2_LEAGUE_ID>",
        "mercatoClosed": true
      }
    },
    "usersIds": [
      "mpg_user_<USER_ID_1>",
      "mpg_user_<USER_ID_2>",
      "mpg_user_<USER_ID_3>",
...
    ],
    "leaguesIds": [
      "mpg_league_<DIVISION_1_LEAGUE_ID>",
      "mpg_league_<DIVISION_2_LEAGUE_ID>"
    ],
    "createdAt": "2019-08-03T14:18:58Z",
    "updatedAt": "2019-08-04T16:25:24Z",
    "suggestedDivisionsSize": 10,
    "lastNotification": 1564843740396,
    "numberUpAndDown": 3,
    "users": {
      "mpg_user_<USER_ID_1>": {
        "firstname": "<FIRST_NAME>",
        "lastname": "<LAST_NAME>",
        "id": "mpg_user_<USER_ID_1>"
      },
      "mpg_user_<USER_ID_2>": {
        "firstname": "<FIRST_NAME>",
        "lastname": "<LAST_NAME>",
        "id": "mpg_user_<USER_ID_2>"
      },
.....
    }
  }
}
`

**Comment by axel3rd** [comment]
@sbahir :  I have implemented the "sub league", considering unchanged any other process (=> nothing about `https://api.monpetitgazon.com/master/league/<LEAGUE_ID>`, don't know if could have impacts).

Please have a try with [mpg-coach-bot-1.6-SNAPSHOT.zip](https://bintray.com/axel3rd/generic-dev/download_file?file_path=mpg-coach-bot-1.6-SNAPSHOT.zip) and let me know if it is working as expected ; reopen otherwise.

By the way, I will wait a couple of day before 1.6 release ; to be sure the behavior is correct.

**Comment by sbahir** [comment]
It's working ! Thanks !

**Comment by axel3rd** [comment]
@sbahir / @thomasGuerin3 : Due to the removal of MPG website (19 July 2021), I should switch all APIs on MPG mobile app (#191 - version 1.8 roadmap).

There is a lot of modifications on API => I can't be sure the *Multiple divisions* will always working fine.

Did you have currently a multiple divisions in game ?

If yes, is it possible to have JSon dashboard content of https://api.mpg.football/dashboard/leagues to have unit test content (technicals details: [Get MPG data for opening a bug](https://github.com/axel3rd/mpg-coach-bot/wiki/Get-MPG-data-for-opening-a-bug)) ? 

Or just confirm content (Json property) have not change: 
https://github.com/axel3rd/mpg-coach-bot/blob/54c6a4c2bcb2ca5709dae0b3160f76b9dbc32297/src/test/resources/__files/mpg.dashboard.multiple-divisions.json#L65-L67

Thanks in advance 😗.
